services:
  docx-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prosedi_docx_service
    ports:
      - "8001:8001"
    environment:
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=prosedi
    volumes:
      - .:/app
    networks:
      - proproyectapi_prosedi_net
    restart: unless-stopped

networks:
  proproyectapi_prosedi_net:
    external: true
